acme_example:
    system:
        site:
            name: name_1
            custom_setting:
                number: 456
                enabled: true
        site_group:
            name: name_2
            custom_setting:
                string: value
                number: 123
                enabled: false
