acme_example:
    system:
        site:
            name: name_1
            custom_setting:
                number: 456
                enabled: true
        site_group:
            name: name_2
            custom_setting:
                string: value
                number: 123
                enabled: false

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $siteAccessService: '@ezpublish.siteaccess_service'

    Acme\ExampleBundle\Controller\:
        resource: '../../acme/ExampleBundle/Controller/'
        tags: [ 'controller.service_arguments' ]
